<?php
include('header.php')
?>
  
<div class="wrapper bodyWrapper " role="main">
    <div class="container ">
    
	        <div class="row breadcrumb-outer">

        	<div class="left-content push-left">
            	<div id="breadcam" role="navigation" aria-label="breadcrumb">
                	<ul class="breadcrumbs"><li><a href="index.html"  class="home"><span>Home</span></a></li> <li class="current">Photo Gallery / 1</li></ul><!-- .breadcrumbs -->                </div>
            </div>
            <div class="right-content push-right">
          <div class="printShare">
            <ul class="">
              <li><a href="#" id="print" title="Print" aria-label="print"><i class="fas fa-print"></i> Print</a></li>
              <li>
                            <span class="share-text"><i class="fas fa-share-alt"></i><b class="off-css">Share</b></span>
						</li>
						<li>
                <a href="https://www.facebook.com/https://www.facebook.com/naveen.kumargahra"
             onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
             target="_blank" title="Share on Facebook" aria-label="Facebook that opens in a new window"><i class="fab fa-facebook-square"></i><b class="off-css">Facebook</b></a>
					 </li>
					 <li>
								<a href="https://twitter.com/NaveenGahra"
            onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
            target="_blank" title="Share on Twitter" aria-label="Twitter that opens in a new window"><i class="fab fa-twitter"></i><b class="off-css">Twitter</b></a>

              </li>
            </ul>
          </div>
        </div>

        </div>
        <div id="SkipContent"></div>
    <div class="row">
      <div class="col-12">
                 
            
			
			
			
			
			
			
			
			<div class="col-12">
<div class="row">
<div class="col-8">
	<h1>Independence Day</h1>
</div>
<div class="col-4">
<div class="viewSwicther right-content"> <a href="#" class="thumbs-view-btn" aria-label="Grid View" title="Grid View"><i class="fas fa-th"></i></a> <a href="#" class="thumbs-list-view-btn" aria-label="List View" title="List View"><i class="fas fa-list"></i></a> </div>
</div>
</div>

<div class="col-12">
<div class="single-glry-discription">
      </div>
</div>
<div class="separator20"></div>
<div class="row thumbs_view">
<div class="">
<div id="photoGalleryBox" class="row gallery-six equal-height thumbs_view">
<div class="col-3 col-4-md reachCont fancyShare">
   <div class="photoGalleryItem clearfix">
      <div class="imageThumb">
      <a href="https://cdn.s3waas.gov.in/s3069059b7ef840f0c74a814ec9237b6ec/uploads/2018/05/2018050511.jpg" class="photoImgContainer fancybox" rel="gallery" title="Indepdence Day">
         <img src="https://cdn.s3waas.gov.in/s3069059b7ef840f0c74a814ec9237b6ec/uploads/bfi_thumb/2018050511-npq1ncvhjwdsfkmwjtdwtg8of4gn4je2sfhs463g0w.jpg" alt="Indepdence_Day">
      </a>
      </div>
      <div class="shareGalleryContainer clearfix">
         <p>Indepdence Day</p>
          				<a href="https://cdn.s3waas.gov.in/s3069059b7ef840f0c74a814ec9237b6ec/uploads/2018/05/2018050511.jpg" class="shareContentItem fancybox" title="Indepdence Day">
				<i class="fas fa-search-plus"></i> Zoom
			</a>
			
      </div>
   </div>
</div>
</div>
</div>

</div>

</div>
			
			
			
			
			
			
			
			
			
			
			
			
			
			
		
                    <!-- end of the loop -->
          
              </div>
          </div>
  </div>
</div>
<?php
include('footer.php')
?>
</body>
</html>

<!-- Dynamic page generated in 0.390 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2019-04-16 16:44:39 -->

<!-- super cache -->