<?php
include('header.php')
?>
<div class="wrapper bodyWrapper " role="main">
    <div class="container ">
    
	        <div class="row breadcrumb-outer">

        	<div class="left-content push-left">
            	<div id="breadcam" role="navigation" aria-label="breadcrumb">
                	<ul class="breadcrumbs"><li><a href="index.html"  class="home"><span>Home</span></a></li> <li class="current">History of Gahra</li></ul><!-- .breadcrumbs -->                </div>
            </div>
            <div class="right-content push-right">
          <div class="printShare">
            <ul class="">
              <li><a href="#" id="print" title="Print" aria-label="print"><i class="fas fa-print"></i> Print</a></li>
              <li>
                            <span class="share-text"><i class="fas fa-share-alt"></i><b class="off-css">Share</b></span>
						</li>
						<li>
                <a href="https://www.facebook.com/"
             onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
             target="_blank" title="Share on Facebook" aria-label="Facebook that opens in a new window"><i class="fab fa-facebook-square"></i><b class="off-css">Facebook</b></a>
					 </li>
					 <li>
								<a href="https://twitter.com/"
            onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
            target="_blank" title="Share on Twitter" aria-label="Twitter that opens in a new window"><i class="fab fa-twitter"></i><b class="off-css">Twitter</b></a>

              </li>
            </ul>
          </div>
        </div>

        </div>
        <div id="SkipContent"></div>
    <div class="row">
      <div class="col-12">
                  
          <div class="row">
      <div class="col-12">
                  
            <h1>Gahra's History</h1><div id="post-1532" class="post-1532 page type-page status-publish hentry">
	<div class="row">
      <div class="col-12">
                  
            <h1>History</h1><div id="post-2733" class="post-2733 page type-page status-publish hentry">
		<div class="vc_row wpb_row vc_row-fluid"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner "><div class="wpb_wrapper">
	<div class="wpb_text_column wpb_content_element ">
		<div class="wpb_wrapper">
			<p class="text-justify">Gahra is a Village in Kanina Tehsil in Mahendragarh District of Haryana State, India. It belongs to Gurgaon Division . It is located 47 KM towards North from District head quarters Narnaul. 12 KM from Kanina. 312 KM from State capital Chandigarh 

Gahra Pin code is 123027 and postal head office is Kanina . 

Sihor ( 3 KM ) , Kotia ( 3 KM ) , Kanina ( 4 KM ) , Karira ( 4 KM ) , Unhani ( 5 KM ) are the nearby Villages to Gahra. Gahra is surrounded by Nahar Tehsil towards East , Mahendragarh Tehsil towards west , Jatusana Tehsil towards East , Khol At Rewari Tehsil towards South . 

Mahendragarh , Charkhi Dadri , Rewari , Narnaul are the near by Cities to Gahra.	

This Place is in the border of the Mahendragarh District and Rewari District. Rewari District Nahar is East towards this place . Also it is in the Border of other district Jhajjar .

<h2>2011 Cencus Details</h2>
<p class="text-justify">Gahra Local Language is Hindi. Gahra Village Total population is 1942 and number of houses are 365. Female Population is 48.2%. Village literacy rate is 72.3% and the Female Literacy rate is 31.4%.</p>


		</div>
	</div>
</div></div></div></div>

</div>
                    <!-- end of the loop -->
          
              </div>
          </div>

</div>
                    <!-- end of the loop -->
          
              </div>
          </div>
</div>
                    <!-- end of the loop -->
          
              </div>
          </div>
  </div>
</div>
<?php
include('footer.php')
?>
</body>
</html>

<!-- Dynamic page generated in 0.390 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2019-04-16 16:44:39 -->

<!-- super cache -->