<?php
include('header.php')
?>
<div class="wrapper bodyWrapper " role="main">
    <div class="container ">
    
	        <div class="row breadcrumb-outer">

        	<div class="left-content push-left">
            	<div id="breadcam" role="navigation" aria-label="breadcrumb">
                	<ul class="breadcrumbs"><li><a href="index.html"  class="home"><span>Home</span></a></li> <li class="current">Profile</li></ul><!-- .breadcrumbs -->                </div>
            </div>
            <div class="right-content push-right">
          <div class="printShare">
            <ul class="">
              <li><a href="#" id="print" title="Print" aria-label="print"><i class="fas fa-print"></i> Print</a></li>
              <li>
                            <span class="share-text"><i class="fas fa-share-alt"></i><b class="off-css">Share</b></span>
						</li>
						<li>
                <a href="https://www.facebook.com/"
             onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
             target="_blank" title="Share on Facebook" aria-label="Facebook that opens in a new window"><i class="fab fa-facebook-square"></i><b class="off-css">Facebook</b></a>
					 </li>
					 <li>
								<a href="https://twitter.com/"
            onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
            target="_blank" title="Share on Twitter" aria-label="Twitter that opens in a new window"><i class="fab fa-twitter"></i><b class="off-css">Twitter</b></a>

              </li>
            </ul>
          </div>
        </div>

        </div>
        <div id="SkipContent"></div>
    <div class="row">
      <div class="col-12">
                  
            <h1>Naveen Yadav</h1><div id="post-1511" class="post-1511 page type-page status-publish hentry">
		<div class="wpb_wrapper">
			<p class="text-justify">I am an Assistant Section Officer in ministries of Delhi. I have done my B.Tech from Cluster Innovation Center Delhi University,Delhi. Then I cleared SSC-CGL exam and got my favourite post ASO. Normally I am from Gahra which is a village in mahendergarh district of Haryana ( 123027 ). I proud to be a villager of Gahra. My best language is Haryanvi.</p>
<p>I welcome your views &amp; suggestions for further improvements.</p>
<p>Sh. Naveen Yadav, ASO<br>
Assistant Section Officer, Delhi<br>
Phone: 8059393996<br>
Instagram: nvn.gahra<br>
Email: nkgahra0395@gmail.com</p>

		</div>
</div>
                    <!-- end of the loop -->
          
              </div>
          </div>
  </div>
</div>
<?php
include('footer.php')
?>
</body>
</html>

<!-- Dynamic page generated in 0.390 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2019-04-16 16:44:39 -->

<!-- super cache -->