<?php
include('header.php')
?>
  
<div class="wrapper bodyWrapper " role="main">
    <div class="container ">
    
	        <div class="row breadcrumb-outer">

        	<div class="left-content push-left">
            	<div id="breadcam" role="navigation" aria-label="breadcrumb">
                	<ul class="breadcrumbs"><li><a href="index.html"  class="home"><span>Home</span></a></li> <li class="current">Village Map</li></ul><!-- .breadcrumbs -->                </div>
            </div>
            <div class="right-content push-right">
          <div class="printShare">
            <ul class="">
              <li><a href="#" id="print" title="Print" aria-label="print"><i class="fas fa-print"></i> Print</a></li>
              <li>
                            <span class="share-text"><i class="fas fa-share-alt"></i><b class="off-css">Share</b></span>
						</li>
						<li>
                <a href="https://www.facebook.com/https://www.facebook.com/naveen.kumargahra"
             onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
             target="_blank" title="Share on Facebook" aria-label="Facebook that opens in a new window"><i class="fab fa-facebook-square"></i><b class="off-css">Facebook</b></a>
					 </li>
					 <li>
								<a href="https://twitter.com/NaveenGahra"
            onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
            target="_blank" title="Share on Twitter" aria-label="Twitter that opens in a new window"><i class="fab fa-twitter"></i><b class="off-css">Twitter</b></a>

              </li>
            </ul>
          </div>
        </div>

        </div>
        <div id="SkipContent"></div>
    <div class="row">
      <div class="col-12">
                 <div style="overflow:hidden;width: 1250px;position: relative;">
				 <iframe width="1250" height="440" src="https://maps.google.com/maps?width=700&amp;height=440&amp;hl=en&amp;q=gahra%2C%20haryana+(Village%20Gahra%2C%20Haryana)&amp;ie=UTF8&amp;t=&amp;z=16&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
				 <div style="position: absolute;width: 80%;bottom: 10px;left: 0;right: 0;margin-left: auto;margin-right: auto;color: #000;text-align: center;"><small style="line-height: 1.8;font-size: 2px;background: #fff;">Powered by <a href="https://embedgooglemaps.com/it/">Naveen Yadav</a> & <a href="https://and-route.com/nl/">Gahra, Haryana</a></small></div>
				 <style>#gmap_canvas img{max-width:none!important;background:none!important}</style></div><br />
            
		
                    <!-- end of the loop -->
          
              </div>
          </div>
  </div>
</div>
<?php
include('footer.php')
?>
</body>
</html>

<!-- Dynamic page generated in 0.390 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2019-04-16 16:44:39 -->

<!-- super cache -->