<?php
include('header.php')
?>
<div class="wrapper bodyWrapper " role="main">
    <div class="container ">
    
	        <div class="row breadcrumb-outer">

        	<div class="left-content push-left">
            	<div id="breadcam" role="navigation" aria-label="breadcrumb">
                	<ul class="breadcrumbs"><li><a href="index.html"><span>Home</span></a></li> <li class="current">Village Profile</li></ul><!-- .breadcrumbs -->                </div>
            </div>
            <div class="right-content push-right">
          <div class="printShare">
            <ul class="">
              <li><a href="#" id="print" title="Print" aria-label="print"><i class="fas fa-print"></i> Print</a></li>
              <li>
                            <span class="share-text"><i class="fas fa-share-alt"></i><b class="off-css">Share</b></span>
						</li>
						<li>
                <a href="https://www.facebook.com/"
             onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
             target="_blank" title="Share on Facebook" aria-label="Facebook that opens in a new window"><i class="fab fa-facebook-square"></i><b class="off-css">Facebook</b></a>
					 </li>
					 <li>
								<a href="https://twitter.com/"
            onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
            target="_blank" title="Share on Twitter" aria-label="Twitter that opens in a new window"><i class="fab fa-twitter"></i><b class="off-css">Twitter</b></a>

              </li>
            </ul>
          </div>
        </div>

        </div>
        <div id="SkipContent"></div>
    <div class="row">
      <div class="col-12">
                  
            <div class="row">
      <div class="col-12">
                  
            <h1>Village Profile</h1><div id="post-22191" class="post-22191 page type-page status-publish hentry">
		<p class="text-justify">Gahra is a village in Kanina on an approach road 4 km in Mahendragarh District of Haryana State, India. It is located 47 km to the north of District headquarters Narnaul. 4 km from Kanina. 312 km from State capital Chandigarh.

Gahra Pin code is 123027 and the postal head office is Kanina.</p>
<h2>Location</h2>
<p class="text-justify">Garha is located at 28.36°N 76.31°E.Garha has an average elevation of 245 metres (803 feet). It borders Karoli, Bawwa, Kanina, and Kotia villages. Mahendragarh, Charkhi Dadri, Rewari, Narnaul are the nearby cities to Gahra.

The temperature can go as high as 46.5 degrees Celsius from May to July. Winter is from November to February, and the temperature can fall to 5 degrees Celsius in December and January. The village is in the Mahendragarh district and has dust storms in summer. Rugged hilly terrain of Aravali ranges as well as sandy dunes are found in nearby villages.

The overall climate is dry. Rain falls from July to September. A little rain is experienced during winter also.

Gahra is nearly 22 km away from district mahendergarh and nearly 42 km away from rewari district and it is nearly 150km away from the national capital.</p>
<h2>Demographics</h2>
<p class="text-justify">According to the 2011 census, the population of Gahra village is 2300. The literacy rate of Bhiwani is 88.9%.</p>
<p class="text-justify">

</p></div>
                    <!-- end of the loop -->
          
              </div>
          </div>

		</div>
</div>
                    <!-- end of the loop -->
          
              </div>
          </div>
  </div>
</div><?php
include('footer.php')
?>

</body>
</html>

<!-- Dynamic page generated in 0.390 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2019-04-16 16:44:39 -->

<!-- super cache -->