<?php
include('header.php')
?>
<div class="wrapper bodyWrapper " role="main">
    <div class="container ">
    
	        <div class="row breadcrumb-outer">

        	<div class="left-content push-left">
            	<div id="breadcam" role="navigation" aria-label="breadcrumb">
                	<ul class="breadcrumbs"><li><a href="index.html"  class="home"><span>Home</span></a></li> <li class="current">Village at a Glance</li></ul><!-- .breadcrumbs -->                </div>
            </div>
            <div class="right-content push-right">
          <div class="printShare">
            <ul class="">
              <li><a href="#" id="print" title="Print" aria-label="print"><i class="fas fa-print"></i> Print</a></li>
              <li>
                            <span class="share-text"><i class="fas fa-share-alt"></i><b class="off-css">Share</b></span>
						</li>
						<li>
                <a href="https://www.facebook.com/"
             onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
             target="_blank" title="Share on Facebook" aria-label="Facebook that opens in a new window"><i class="fab fa-facebook-square"></i><b class="off-css">Facebook</b></a>
					 </li>
					 <li>
								<a href="https://twitter.com/"
            onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
            target="_blank" title="Share on Twitter" aria-label="Twitter that opens in a new window"><i class="fab fa-twitter"></i><b class="off-css">Twitter</b></a>

              </li>
            </ul>
          </div>
        </div>

        </div>
        <div id="SkipContent"></div>
    <div class="row">
      <div class="col-12">
                  
          <div class="row">
      <div class="col-12">
                  
            <h1>Gahra at a Glance</h1><div id="post-1532" class="post-1532 page type-page status-publish hentry">
		<table style="table-layout: fixed;">
<thead>
<tr>
<th>S.no</th>
<th>Name</th>
<th>Detail</th>
</tr>
</thead>
<tbody>
<tr>
<td data-th="S.no"><span class="bt-content">1</span></td>
<td data-th="Name"><span class="bt-content">Area</span></td>
<td data-th="Detail"><span class="bt-content">5.12 sq km</span></td>
</tr>
<tr>
<td data-th="S.no"><span class="bt-content">2</span></td>
<td data-th="Name"><span class="bt-content">Male</span></td>
<td data-th="Detail"><span class="bt-content">1200</span></td>
</tr>
<tr>
<td data-th="S.no"><span class="bt-content">3</span></td>
<td data-th="Name"><span class="bt-content">Female</span></td>
<td data-th="Detail"><span class="bt-content">1100</span></td>
</tr>
<tr>
<td data-th="S.no"><span class="bt-content">4</span></td>
<td data-th="Name"><span class="bt-content">Population</span></td>
<td data-th="Detail"><span class="bt-content">2300</span></td>
</tr>
<tr>
<td data-th="S.no"><span class="bt-content">5</span></td>
<td data-th="Name"><span class="bt-content">Literacy</span></td>
<td data-th="Detail"><span class="bt-content">88.9%</span></td>
</tr>
</tbody>
</table>

</div>
                    <!-- end of the loop -->
          
              </div>
          </div>
</div>
                    <!-- end of the loop -->
          
              </div>
          </div>
  </div>
</div>
<?php
include('footer.php')
?>
</body>
</html>

<!-- Dynamic page generated in 0.390 seconds. -->
<!-- Cached page generated by WP-Super-Cache on 2019-04-16 16:44:39 -->

<!-- super cache -->